@url = http://localhost:3000
###
# Test connection
POST {{url}}
Content-Type: application/json

{
  "type": "std:test-connection",
  "input": {},
  "config": {{config}}
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/x-ndjson
date: Sat, 30 Nov 2024 16:05:17 GMT
connection: close
transfer-encoding: chunked
###
# Discover schema
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:discover-schema",
  "input": {},
  "config": {{config}}
}

HTTP/1.1 500  - Internal Server Error
x-powered-by: Express
content-type: application/x-ndjson
date: Mon, 13 Jan 2025 13:28:59 GMT
connection: close
transfer-encoding: chunked
###
# Push contents
POST {{url}}
Content-Type: application/json

{
  "type": "std:push:contents",
  "input": {},
  "config": {{config}}
}
###
# Account list
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:list",
  "input": {},
  "config": {{config}}
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/x-ndjson
date: Mon, 09 Jun 2025 13:01:13 GMT
connection: close
transfer-encoding: chunked
###
# Account read
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:read",
  "input": {
    "identity": "a58188c4-3cb0-4620-bbcd-065850837446"
  },
  "config": {{config}}
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/x-ndjson
date: Wed, 18 Jun 2025 08:54:48 GMT
connection: close
transfer-encoding: chunked
###
# Entitlement list
POST {{url}}
Content-Type: application/json

{
  "type": "std:entitlement:list",
  "input": {
        "type": "role"
    },
  "config": {{config}}
}
###
# Entitlement read
POST {{url}}
Content-Type: application/json

{
  "type": "std:entitlement:read",
  "input": {
        "identity": "fc16aee3-0359-4d46-b746-b36459211660"
    },
  "config": {{config}}
}
###
# Account disable
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:disable",
  "input": {
    "identity": "993",
    "key": { "simple": { "id": "993" } }
  },
"config": {{config}}
}
###
# Account enable
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:enable",
  "input": {
    "identity": "993"
  },
  "config": {{config}}
}
###
# Account update
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:update",
  "input": {"changes":[{"attribute":"workflows","op":"Add","value":"dc1b7eef-52cb-4784-b1c5-d9dd2550962d"}], "identity": "87f9f303-70b4-4b21-a4f9-7b4515755e9f"},
  "config": {{config}}
}
###
# Account create
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:create",
  "input": {
    "attributes":{"email":"gast2@inagaddavida.de","last_name":"gast2","login":"gast2@inagaddavida.de","login_name":"gast2@inagaddavida.de","name":"gast2","person_id":"gast2_inagaddavida.de#EXT#@vj42.onmicrosoft.com","status":"Inactive","workflows":"b33ca9cc-c9a0-4eb7-91c8-3d6320419a81"}
  },
  "config": {{config}}
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/x-ndjson
date: Mon, 02 Jun 2025 12:05:01 GMT
connection: close
transfer-encoding: chunked